import "./globals.css";
import { Provider } from "react-redux";
import { store } from "./redux/store";
import Context from "./context";
import AppContext from "./context";
export const metadata = {
  title: "Block Trace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppContext>
          {children}
        </AppContext>
      </body>
    </html>
  );
}
